"""add_intake_tables

Revision ID: a873c2277507
Revises: 
Create Date: 2026-03-12 14:26:38.186312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a873c2277507'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_keyword', sa.String(length=255), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('research_only', 'scored', 'cad_generated', 'manufacturing_simulated', 'listing_generated', 'prototype_candidate', 'archived', name='productstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index('ix_products_status_updated', 'products', ['status', 'updated_at'], unique=False)
    op.create_table('cad_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('scad_code', sa.Text(), nullable=True),
    sa.Column('scad_file_path', sa.String(length=512), nullable=True),
    sa.Column('stl_file_path', sa.String(length=512), nullable=True),
    sa.Column('generation_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('short_pitch', sa.String(length=500), nullable=True),
    sa.Column('bullet_points_json', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('suggested_price', sa.Float(), nullable=True),
    sa.Column('photo_prompt', sa.Text(), nullable=True),
    sa.Column('why_it_could_sell', sa.Text(), nullable=True),
    sa.Column('differentiation_angle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.Column('competition_score', sa.Float(), nullable=False),
    sa.Column('manufacturing_score', sa.Float(), nullable=False),
    sa.Column('margin_score', sa.Float(), nullable=False),
    sa.Column('differentiation_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('scoring_notes', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('listed_price', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('estimated_sales', sa.Integer(), nullable=True),
    sa.Column('competitor_count', sa.Integer(), nullable=True),
    sa.Column('listing_count', sa.Integer(), nullable=True),
    sa.Column('listing_age_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturing_simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cad_model_id', sa.Integer(), nullable=True),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('layer_height', sa.Float(), nullable=False),
    sa.Column('infill', sa.Float(), nullable=False),
    sa.Column('nozzle_size', sa.Float(), nullable=False),
    sa.Column('estimated_print_time_minutes', sa.Float(), nullable=True),
    sa.Column('estimated_material_grams', sa.Float(), nullable=True),
    sa.Column('estimated_filament_cost', sa.Float(), nullable=True),
    sa.Column('supports_required', sa.Boolean(), nullable=False),
    sa.Column('recommended_orientation', sa.String(length=100), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('simulated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cad_model_id'], ['cad_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_intakes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('raw_collected', 'enriching', 'brief_drafted', 'brief_approved', 'rejected', 'cad_queued', name='intakestatus'), nullable=False),
    sa.Column('trigger_mode', sa.Enum('etsy_url', 'erank_paste', 'manual', name='triggermode'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_keyword', sa.String(length=256), nullable=True),
    sa.Column('raw_title', sa.String(length=512), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('raw_tags', sa.JSON(), nullable=True),
    sa.Column('raw_price_usd', sa.Float(), nullable=True),
    sa.Column('raw_review_count', sa.Integer(), nullable=True),
    sa.Column('raw_rating', sa.Float(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('visual_summary_json', sa.JSON(), nullable=True),
    sa.Column('text_extraction_json', sa.JSON(), nullable=True),
    sa.Column('draft_brief_json', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_detail_json', sa.JSON(), nullable=True),
    sa.Column('enrichment_attempt_count', sa.Integer(), nullable=False),
    sa.Column('approved_brief_json', sa.JSON(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('cad_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cad_model_id'], ['cad_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_intakes_status'), 'product_intakes', ['status'], unique=False)
    op.create_index('ix_product_intakes_status_created', 'product_intakes', ['status', 'created_at'], unique=False)
    op.create_table('intake_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intake_id', sa.String(length=36), nullable=False),
    sa.Column('image_index', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('vision_analysis_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['product_intakes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_images_intake_id'), 'intake_images', ['intake_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intake_images_intake_id'), table_name='intake_images')
    op.drop_table('intake_images')
    op.drop_index('ix_product_intakes_status_created', table_name='product_intakes')
    op.drop_index(op.f('ix_product_intakes_status'), table_name='product_intakes')
    op.drop_table('product_intakes')
    op.drop_table('manufacturing_simulations')
    op.drop_table('research_data')
    op.drop_table('product_notes')
    op.drop_table('opportunity_scores')
    op.drop_table('listings')
    op.drop_table('cad_models')
    op.drop_index('ix_products_status_updated', table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_table('imports')
    # ### end Alembic commands ###
